---
abstract: 'Moo eXtension to inject plugins to exist objects as a role'
author:
  - 'Huo Linhe <huolinhe@berrygenomics.com>'
build_requires:
  Module::Build: '0.28'
  Module::Find: '0'
  Moo: '0'
  MooX: '0'
  Moops: '0'
  Role::Tiny: '0'
  Test::More: '0'
  Test::Pod: '0'
  lib: '0'
configure_requires:
  Module::Build: '0.28'
dynamic_config: 1
generated_by: 'Module::Build version 0.4211, CPAN::Meta::Converter version 2.150001'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: MooX-Object-Pluggable
provides:
  MooX::Object::Pluggable:
    file: lib/MooX/Object/Pluggable.pm
    version: v0.0.4
requires:
  Modern::Perl: '0'
  Module::Pluggable::Object: '0'
  Moo::Role: '0'
  Scalar::Util: '0'
  namespace::clean: '0'
resources:
  license: http://dev.perl.org/licenses/
version: v0.0.4
